# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/c_and_b.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CAndBForm(object):
    def setupUi(self, CAndBForm):
        CAndBForm.setObjectName("CAndBForm")
        CAndBForm.resize(392, 455)
        self.verticalLayout = QtWidgets.QVBoxLayout(CAndBForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(CAndBForm)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.calCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.calCheckBox.setObjectName("calCheckBox")
        self.gridLayout_2.addWidget(self.calCheckBox, 0, 1, 1, 1)
        self.calibrateButton = QtWidgets.QPushButton(self.groupBox)
        self.calibrateButton.setObjectName("calibrateButton")
        self.gridLayout_2.addWidget(self.calibrateButton, 0, 0, 1, 1)
        self.stopBgPushButton = QtWidgets.QPushButton(self.groupBox)
        self.stopBgPushButton.setObjectName("stopBgPushButton")
        self.gridLayout_2.addWidget(self.stopBgPushButton, 1, 3, 1, 1)
        self.calDateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.calDateTimeEdit.setEnabled(False)
        self.calDateTimeEdit.setCalendarPopup(True)
        self.calDateTimeEdit.setObjectName("calDateTimeEdit")
        self.gridLayout_2.addWidget(self.calDateTimeEdit, 0, 2, 1, 1)
        self.bgCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.bgCheckBox.setObjectName("bgCheckBox")
        self.gridLayout_2.addWidget(self.bgCheckBox, 1, 1, 1, 1)
        self.stopCalPushButton = QtWidgets.QPushButton(self.groupBox)
        self.stopCalPushButton.setObjectName("stopCalPushButton")
        self.gridLayout_2.addWidget(self.stopCalPushButton, 0, 3, 1, 1)
        self.backgroundButton = QtWidgets.QPushButton(self.groupBox)
        self.backgroundButton.setObjectName("backgroundButton")
        self.gridLayout_2.addWidget(self.backgroundButton, 1, 0, 1, 1)
        self.bgDateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.bgDateTimeEdit.setEnabled(False)
        self.bgDateTimeEdit.setCalendarPopup(True)
        self.bgDateTimeEdit.setObjectName("bgDateTimeEdit")
        self.gridLayout_2.addWidget(self.bgDateTimeEdit, 1, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.groupBox_2 = QtWidgets.QGroupBox(CAndBForm)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.calLocalTimeLabel = QtWidgets.QLabel(self.groupBox_2)
        self.calLocalTimeLabel.setObjectName("calLocalTimeLabel")
        self.gridLayout_3.addWidget(self.calLocalTimeLabel, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 4, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.firstScheduledCalibrationDateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox_2)
        self.firstScheduledCalibrationDateTimeEdit.setEnabled(True)
        self.firstScheduledCalibrationDateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 4), QtCore.QTime(13, 0, 0)))
        self.firstScheduledCalibrationDateTimeEdit.setCalendarPopup(True)
        self.firstScheduledCalibrationDateTimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.firstScheduledCalibrationDateTimeEdit.setObjectName("firstScheduledCalibrationDateTimeEdit")
        self.gridLayout_3.addWidget(self.firstScheduledCalibrationDateTimeEdit, 1, 1, 1, 1)
        self.bgLocalTimeLabel = QtWidgets.QLabel(self.groupBox_2)
        self.bgLocalTimeLabel.setObjectName("bgLocalTimeLabel")
        self.gridLayout_3.addWidget(self.bgLocalTimeLabel, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.calibrationIntervalSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.calibrationIntervalSpinBox.setMinimum(1)
        self.calibrationIntervalSpinBox.setProperty("value", 28)
        self.calibrationIntervalSpinBox.setObjectName("calibrationIntervalSpinBox")
        self.gridLayout_3.addWidget(self.calibrationIntervalSpinBox, 1, 3, 1, 1)
        self.enableScheduleButton = QtWidgets.QPushButton(self.groupBox_2)
        self.enableScheduleButton.setCheckable(True)
        self.enableScheduleButton.setObjectName("enableScheduleButton")
        self.gridLayout_3.addWidget(self.enableScheduleButton, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 2, 1, 1)
        self.firstScheduledBackgroundDateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox_2)
        self.firstScheduledBackgroundDateTimeEdit.setEnabled(True)
        self.firstScheduledBackgroundDateTimeEdit.setCalendarPopup(True)
        self.firstScheduledBackgroundDateTimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.firstScheduledBackgroundDateTimeEdit.setObjectName("firstScheduledBackgroundDateTimeEdit")
        self.gridLayout_3.addWidget(self.firstScheduledBackgroundDateTimeEdit, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.backgroundIntervalSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.backgroundIntervalSpinBox.setMinimum(2)
        self.backgroundIntervalSpinBox.setProperty("value", 84)
        self.backgroundIntervalSpinBox.setObjectName("backgroundIntervalSpinBox")
        self.gridLayout_3.addWidget(self.backgroundIntervalSpinBox, 4, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 5, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(CAndBForm)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.flushSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.flushSpinBox.setMaximum(48)
        self.flushSpinBox.setProperty("value", 12)
        self.flushSpinBox.setObjectName("flushSpinBox")
        self.gridLayout.addWidget(self.flushSpinBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.injectSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.injectSpinBox.setMaximum(48)
        self.injectSpinBox.setProperty("value", 6)
        self.injectSpinBox.setObjectName("injectSpinBox")
        self.gridLayout.addWidget(self.injectSpinBox, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.backgroundSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.backgroundSpinBox.setProperty("value", 24)
        self.backgroundSpinBox.setObjectName("backgroundSpinBox")
        self.gridLayout.addWidget(self.backgroundSpinBox, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.scheduleEngagedLabel = QtWidgets.QLabel(CAndBForm)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.scheduleEngagedLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.scheduleEngagedLabel.setFont(font)
        self.scheduleEngagedLabel.setText("")
        self.scheduleEngagedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.scheduleEngagedLabel.setObjectName("scheduleEngagedLabel")
        self.verticalLayout.addWidget(self.scheduleEngagedLabel)

        self.retranslateUi(CAndBForm)
        QtCore.QMetaObject.connectSlotsByName(CAndBForm)

    def retranslateUi(self, CAndBForm):
        _translate = QtCore.QCoreApplication.translate
        CAndBForm.setWindowTitle(_translate("CAndBForm", "Form"))
        self.groupBox.setTitle(_translate("CAndBForm", "Once-off"))
        self.calCheckBox.setText(_translate("CAndBForm", "later at"))
        self.calibrateButton.setText(_translate("CAndBForm", "Calibrate"))
        self.stopBgPushButton.setText(_translate("CAndBForm", "Stop background"))
        self.calDateTimeEdit.setDisplayFormat(_translate("CAndBForm", "yyyy-MM-dd hh:mm"))
        self.bgCheckBox.setText(_translate("CAndBForm", "later at"))
        self.stopCalPushButton.setText(_translate("CAndBForm", "Stop calibration"))
        self.backgroundButton.setText(_translate("CAndBForm", "Background"))
        self.bgDateTimeEdit.setDisplayFormat(_translate("CAndBForm", "yyyy-MM-dd hh:mm"))
        self.groupBox_2.setTitle(_translate("CAndBForm", "Scheduled"))
        self.calLocalTimeLabel.setText(_translate("CAndBForm", "---"))
        self.label_9.setText(_translate("CAndBForm", "Interval (days)"))
        self.label_8.setText(_translate("CAndBForm", "Start (UTC)"))
        self.label_4.setText(_translate("CAndBForm", "Start (UTC)"))
        self.firstScheduledCalibrationDateTimeEdit.setDisplayFormat(_translate("CAndBForm", "yyyy-MM-dd hh:mm"))
        self.bgLocalTimeLabel.setText(_translate("CAndBForm", "---"))
        self.label_6.setText(_translate("CAndBForm", "Calibration"))
        self.enableScheduleButton.setText(_translate("CAndBForm", "Enable Schedule"))
        self.label_5.setText(_translate("CAndBForm", "Interval (days)"))
        self.firstScheduledBackgroundDateTimeEdit.setDisplayFormat(_translate("CAndBForm", "yyyy-MM-dd hh:mm"))
        self.label_7.setText(_translate("CAndBForm", "Background"))
        self.label_10.setText(_translate("CAndBForm", "Local time"))
        self.label_11.setText(_translate("CAndBForm", "Local time"))
        self.groupBox_3.setTitle(_translate("CAndBForm", "Parameters"))
        self.label.setText(_translate("CAndBForm", "Flush duration (hours):"))
        self.label_2.setText(_translate("CAndBForm", "Inject duration(hours):"))
        self.label_3.setText(_translate("CAndBForm", "Background duration(hours):"))

