# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/c_and_b.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CAndBForm(object):
    def setupUi(self, CAndBForm):
        CAndBForm.setObjectName("CAndBForm")
        CAndBForm.resize(560, 710)
        self.verticalLayout = QtWidgets.QVBoxLayout(CAndBForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(CAndBForm)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.startLaterCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.startLaterCheckBox.setToolTip("")
        self.startLaterCheckBox.setObjectName("startLaterCheckBox")
        self.gridLayout_2.addWidget(self.startLaterCheckBox, 4, 1, 1, 1)
        self.startStopPushButton = QtWidgets.QPushButton(self.groupBox)
        self.startStopPushButton.setCheckable(True)
        self.startStopPushButton.setObjectName("startStopPushButton")
        self.gridLayout_2.addWidget(self.startStopPushButton, 8, 1, 1, 1)
        self.calbgDateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.calbgDateTimeEdit.setEnabled(False)
        self.calbgDateTimeEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1752, 9, 14), QtCore.QTime(14, 0, 0)))
        self.calbgDateTimeEdit.setMinimumTime(QtCore.QTime(14, 0, 0))
        self.calbgDateTimeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.calbgDateTimeEdit.setCalendarPopup(True)
        self.calbgDateTimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.calbgDateTimeEdit.setObjectName("calbgDateTimeEdit")
        self.gridLayout_2.addWidget(self.calbgDateTimeEdit, 5, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 4, 0, 1, 1)
        self.calbgLocalTimeLabel = QtWidgets.QLabel(self.groupBox)
        self.calbgLocalTimeLabel.setObjectName("calbgLocalTimeLabel")
        self.gridLayout_2.addWidget(self.calbgLocalTimeLabel, 6, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 5, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 6, 0, 1, 1)
        self.operationTypeComboBox = QtWidgets.QComboBox(self.groupBox)
        self.operationTypeComboBox.setObjectName("operationTypeComboBox")
        self.gridLayout_2.addWidget(self.operationTypeComboBox, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.groupBox_2 = QtWidgets.QGroupBox(CAndBForm)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.calibrationIntervalSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.calibrationIntervalSpinBox.setMinimum(0)
        self.calibrationIntervalSpinBox.setProperty("value", 28)
        self.calibrationIntervalSpinBox.setObjectName("calibrationIntervalSpinBox")
        self.gridLayout_3.addWidget(self.calibrationIntervalSpinBox, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.backgroundIntervalSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.backgroundIntervalSpinBox.setMinimum(0)
        self.backgroundIntervalSpinBox.setProperty("value", 84)
        self.backgroundIntervalSpinBox.setObjectName("backgroundIntervalSpinBox")
        self.gridLayout_3.addWidget(self.backgroundIntervalSpinBox, 1, 1, 1, 1)
        self.enableScheduleButton = QtWidgets.QPushButton(self.groupBox_2)
        self.enableScheduleButton.setCheckable(True)
        self.enableScheduleButton.setObjectName("enableScheduleButton")
        self.gridLayout_3.addWidget(self.enableScheduleButton, 3, 1, 1, 1)
        self.cal_bg_start_times_layout = QtWidgets.QVBoxLayout()
        self.cal_bg_start_times_layout.setObjectName("cal_bg_start_times_layout")
        self.gridLayout_3.addLayout(self.cal_bg_start_times_layout, 2, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(CAndBForm)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.flushSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.flushSpinBox.setMaximum(48)
        self.flushSpinBox.setProperty("value", 12)
        self.flushSpinBox.setObjectName("flushSpinBox")
        self.gridLayout.addWidget(self.flushSpinBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.injectSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.injectSpinBox.setMaximum(48)
        self.injectSpinBox.setProperty("value", 6)
        self.injectSpinBox.setObjectName("injectSpinBox")
        self.gridLayout.addWidget(self.injectSpinBox, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.backgroundSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.backgroundSpinBox.setProperty("value", 24)
        self.backgroundSpinBox.setObjectName("backgroundSpinBox")
        self.gridLayout.addWidget(self.backgroundSpinBox, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.scheduleEngagedLabel = QtWidgets.QLabel(CAndBForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scheduleEngagedLabel.sizePolicy().hasHeightForWidth())
        self.scheduleEngagedLabel.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.scheduleEngagedLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.scheduleEngagedLabel.setFont(font)
        self.scheduleEngagedLabel.setText("")
        self.scheduleEngagedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.scheduleEngagedLabel.setObjectName("scheduleEngagedLabel")
        self.verticalLayout.addWidget(self.scheduleEngagedLabel)

        self.retranslateUi(CAndBForm)
        QtCore.QMetaObject.connectSlotsByName(CAndBForm)

    def retranslateUi(self, CAndBForm):
        _translate = QtCore.QCoreApplication.translate
        CAndBForm.setWindowTitle(_translate("CAndBForm", "Form"))
        self.groupBox.setTitle(_translate("CAndBForm", "Once-off"))
        self.startLaterCheckBox.setText(_translate("CAndBForm", "start later"))
        self.startStopPushButton.setText(_translate("CAndBForm", "Start"))
        self.calbgDateTimeEdit.setDisplayFormat(_translate("CAndBForm", "yyyy-MM-dd hh:mm UTC"))
        self.label_14.setText(_translate("CAndBForm", "Type of operation:"))
        self.label_13.setText(_translate("CAndBForm", "Timing:"))
        self.calbgLocalTimeLabel.setText(_translate("CAndBForm", "---"))
        self.label_12.setText(_translate("CAndBForm", " Start time:"))
        self.label_15.setText(_translate("CAndBForm", "(In local Time):"))
        self.groupBox_2.setTitle(_translate("CAndBForm", "Schedule"))
        self.label_9.setText(_translate("CAndBForm", "Background interval"))
        self.calibrationIntervalSpinBox.setSuffix(_translate("CAndBForm", " days"))
        self.label_5.setText(_translate("CAndBForm", "Calibration interval"))
        self.backgroundIntervalSpinBox.setSuffix(_translate("CAndBForm", " days"))
        self.enableScheduleButton.setText(_translate("CAndBForm", "Enable Schedule"))
        self.groupBox_3.setTitle(_translate("CAndBForm", "Parameters"))
        self.label.setText(_translate("CAndBForm", "Flush duration:"))
        self.flushSpinBox.setSuffix(_translate("CAndBForm", " hours"))
        self.label_2.setText(_translate("CAndBForm", "Inject duration:"))
        self.injectSpinBox.setSuffix(_translate("CAndBForm", " hours"))
        self.label_3.setText(_translate("CAndBForm", "Background duration:"))
        self.backgroundSpinBox.setSuffix(_translate("CAndBForm", " hours"))

