# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/system_information.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SystemInformationForm(object):
    def setupUi(self, SystemInformationForm):
        SystemInformationForm.setObjectName("SystemInformationForm")
        SystemInformationForm.resize(347, 697)
        self.verticalLayout = QtWidgets.QVBoxLayout(SystemInformationForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.notLoggingLabel = QtWidgets.QLabel(SystemInformationForm)
        self.notLoggingLabel.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.notLoggingLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.notLoggingLabel.setFont(font)
        self.notLoggingLabel.setText("")
        self.notLoggingLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.notLoggingLabel.setObjectName("notLoggingLabel")
        self.verticalLayout.addWidget(self.notLoggingLabel)
        self.stopLoggingButton = QtWidgets.QPushButton(SystemInformationForm)
        self.stopLoggingButton.setCheckable(True)
        self.stopLoggingButton.setObjectName("stopLoggingButton")
        self.verticalLayout.addWidget(self.stopLoggingButton)
        self.groupBox = QtWidgets.QGroupBox(SystemInformationForm)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.downloadButton = QtWidgets.QPushButton(self.groupBox)
        self.downloadButton.setObjectName("downloadButton")
        self.gridLayout_2.addWidget(self.downloadButton, 6, 1, 1, 2)
        self.queryButton = QtWidgets.QPushButton(self.groupBox)
        self.queryButton.setObjectName("queryButton")
        self.gridLayout_2.addWidget(self.queryButton, 4, 1, 1, 2)
        self.serialPortComboBox = QtWidgets.QComboBox(self.groupBox)
        self.serialPortComboBox.setObjectName("serialPortComboBox")
        self.gridLayout_2.addWidget(self.serialPortComboBox, 3, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 8, 1, 1, 2)
        self.timeSyncButton = QtWidgets.QPushButton(self.groupBox)
        self.timeSyncButton.setObjectName("timeSyncButton")
        self.gridLayout_2.addWidget(self.timeSyncButton, 7, 1, 1, 2)
        self.sendProgramButton = QtWidgets.QPushButton(self.groupBox)
        self.sendProgramButton.setObjectName("sendProgramButton")
        self.gridLayout_2.addWidget(self.sendProgramButton, 9, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.dataLoggerTextBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.dataLoggerTextBrowser.setTabChangesFocus(True)
        self.dataLoggerTextBrowser.setObjectName("dataLoggerTextBrowser")
        self.gridLayout_2.addWidget(self.dataLoggerTextBrowser, 5, 1, 1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(SystemInformationForm)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.queryLabjackButton = QtWidgets.QPushButton(self.groupBox_2)
        self.queryLabjackButton.setObjectName("queryLabjackButton")
        self.verticalLayout_2.addWidget(self.queryLabjackButton)
        self.labjackTextBrowser = QtWidgets.QTextBrowser(self.groupBox_2)
        self.labjackTextBrowser.setTabChangesFocus(True)
        self.labjackTextBrowser.setObjectName("labjackTextBrowser")
        self.verticalLayout_2.addWidget(self.labjackTextBrowser)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.label_2 = QtWidgets.QLabel(SystemInformationForm)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(SystemInformationForm)
        QtCore.QMetaObject.connectSlotsByName(SystemInformationForm)

    def retranslateUi(self, SystemInformationForm):
        _translate = QtCore.QCoreApplication.translate
        SystemInformationForm.setWindowTitle(_translate("SystemInformationForm", "Form"))
        self.stopLoggingButton.setText(_translate("SystemInformationForm", "Stop Logging"))
        self.groupBox.setTitle(_translate("SystemInformationForm", "Data Loggers"))
        self.downloadButton.setText(_translate("SystemInformationForm", "Retrieve Data Logger Program"))
        self.queryButton.setText(_translate("SystemInformationForm", "Query Port"))
        self.label_4.setText(_translate("SystemInformationForm", "Caution: clears data logger memory"))
        self.timeSyncButton.setText(_translate("SystemInformationForm", "Force Clock Sync"))
        self.sendProgramButton.setText(_translate("SystemInformationForm", "Send New Datalogger Program"))
        self.label.setText(_translate("SystemInformationForm", "Serial ports:"))
        self.groupBox_2.setTitle(_translate("SystemInformationForm", "Lab Jacks"))
        self.queryLabjackButton.setText(_translate("SystemInformationForm", "Query Labjacks"))
        self.label_2.setText(_translate("SystemInformationForm", "Run tests to identify Campbell Scientific data loggers and Lab Jacks.  If there are other instruments connected to this computer over serial ports or using other Lab Jacks then the tests here could interfere with them. Logging from the radon detector needs to be suspended before the tests can run."))

