# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/sensitivity_sweep.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SensitivitySweepForm(object):
    def setupUi(self, SensitivitySweepForm):
        SensitivitySweepForm.setObjectName("SensitivitySweepForm")
        SensitivitySweepForm.resize(503, 327)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SensitivitySweepForm.sizePolicy().hasHeightForWidth())
        SensitivitySweepForm.setSizePolicy(sizePolicy)
        self.mainVerticalLayout = QtWidgets.QVBoxLayout(SensitivitySweepForm)
        self.mainVerticalLayout.setObjectName("mainVerticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hvSweepGroupBox = QtWidgets.QGroupBox(SensitivitySweepForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hvSweepGroupBox.sizePolicy().hasHeightForWidth())
        self.hvSweepGroupBox.setSizePolicy(sizePolicy)
        self.hvSweepGroupBox.setObjectName("hvSweepGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.hvSweepGroupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtWidgets.QLabel(self.hvSweepGroupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.comboBox = QtWidgets.QComboBox(self.hvSweepGroupBox)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_3 = QtWidgets.QLabel(self.hvSweepGroupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.hvLowSpinBox = QtWidgets.QSpinBox(self.hvSweepGroupBox)
        self.hvLowSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hvLowSpinBox.setMinimum(500)
        self.hvLowSpinBox.setMaximum(1500)
        self.hvLowSpinBox.setSingleStep(10)
        self.hvLowSpinBox.setProperty("value", 800)
        self.hvLowSpinBox.setObjectName("hvLowSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hvLowSpinBox)
        self.label_4 = QtWidgets.QLabel(self.hvSweepGroupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.hvHighSpinBox = QtWidgets.QSpinBox(self.hvSweepGroupBox)
        self.hvHighSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hvHighSpinBox.setMinimum(500)
        self.hvHighSpinBox.setMaximum(1500)
        self.hvHighSpinBox.setSingleStep(10)
        self.hvHighSpinBox.setProperty("value", 1000)
        self.hvHighSpinBox.setObjectName("hvHighSpinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.hvHighSpinBox)
        self.label_2 = QtWidgets.QLabel(self.hvSweepGroupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.hvStepSpinBox = QtWidgets.QSpinBox(self.hvSweepGroupBox)
        self.hvStepSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hvStepSpinBox.setMinimum(10)
        self.hvStepSpinBox.setMaximum(500)
        self.hvStepSpinBox.setSingleStep(5)
        self.hvStepSpinBox.setProperty("value", 50)
        self.hvStepSpinBox.setObjectName("hvStepSpinBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.hvStepSpinBox)
        self.label_5 = QtWidgets.QLabel(self.hvSweepGroupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.hvSecSpinBox = QtWidgets.QSpinBox(self.hvSweepGroupBox)
        self.hvSecSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hvSecSpinBox.setSuffix("")
        self.hvSecSpinBox.setMinimum(10)
        self.hvSecSpinBox.setMaximum(3600)
        self.hvSecSpinBox.setSingleStep(10)
        self.hvSecSpinBox.setProperty("value", 100)
        self.hvSecSpinBox.setObjectName("hvSecSpinBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.hvSecSpinBox)
        self.noiseCheckBox = QtWidgets.QCheckBox(self.hvSweepGroupBox)
        self.noiseCheckBox.setChecked(True)
        self.noiseCheckBox.setObjectName("noiseCheckBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.noiseCheckBox)
        self.horizontalLayout.addWidget(self.hvSweepGroupBox)
        self.statusGroupBox = QtWidgets.QGroupBox(SensitivitySweepForm)
        self.statusGroupBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusGroupBox.sizePolicy().hasHeightForWidth())
        self.statusGroupBox.setSizePolicy(sizePolicy)
        self.statusGroupBox.setFlat(False)
        self.statusGroupBox.setObjectName("statusGroupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.statusGroupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.statusGroupBox)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.hvTargetLabel = QtWidgets.QLabel(self.statusGroupBox)
        font = QtGui.QFont()
        font.setPointSize(31)
        self.hvTargetLabel.setFont(font)
        self.hvTargetLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hvTargetLabel.setObjectName("hvTargetLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.hvTargetLabel)
        self.label_8 = QtWidgets.QLabel(self.statusGroupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.hvMeasuredLabel = QtWidgets.QLabel(self.statusGroupBox)
        font = QtGui.QFont()
        font.setPointSize(31)
        self.hvMeasuredLabel.setFont(font)
        self.hvMeasuredLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hvMeasuredLabel.setObjectName("hvMeasuredLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.hvMeasuredLabel)
        self.instructionLabel = QtWidgets.QLabel(self.statusGroupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.instructionLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.instructionLabel.setFont(font)
        self.instructionLabel.setText("")
        self.instructionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.instructionLabel.setObjectName("instructionLabel")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.instructionLabel)
        self.progressBar = QtWidgets.QProgressBar(self.statusGroupBox)
        self.progressBar.setMinimumSize(QtCore.QSize(207, 0))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.progressBar)
        self.horizontalLayout.addWidget(self.statusGroupBox)
        self.mainVerticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startButton = QtWidgets.QPushButton(SensitivitySweepForm)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_2.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(SensitivitySweepForm)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_2.addWidget(self.stopButton)
        self.mainVerticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(SensitivitySweepForm)
        QtCore.QMetaObject.connectSlotsByName(SensitivitySweepForm)

    def retranslateUi(self, SensitivitySweepForm):
        _translate = QtCore.QCoreApplication.translate
        SensitivitySweepForm.setWindowTitle(_translate("SensitivitySweepForm", "Form"))
        self.hvSweepGroupBox.setTitle(_translate("SensitivitySweepForm", " High Voltage Sweep"))
        self.label_9.setText(_translate("SensitivitySweepForm", "Radon Detector"))
        self.label_3.setText(_translate("SensitivitySweepForm", "From"))
        self.hvLowSpinBox.setSuffix(_translate("SensitivitySweepForm", "V"))
        self.label_4.setText(_translate("SensitivitySweepForm", "To"))
        self.hvHighSpinBox.setSuffix(_translate("SensitivitySweepForm", "V"))
        self.label_2.setText(_translate("SensitivitySweepForm", "Step"))
        self.hvStepSpinBox.setSuffix(_translate("SensitivitySweepForm", "V"))
        self.label_5.setText(_translate("SensitivitySweepForm", "Seconds per step"))
        self.noiseCheckBox.setToolTip(_translate("SensitivitySweepForm", "Any noisy measurements (ULD counts > 0) are repeated with this option enabled"))
        self.noiseCheckBox.setText(_translate("SensitivitySweepForm", "Exclude Noisy"))
        self.statusGroupBox.setTitle(_translate("SensitivitySweepForm", "Status"))
        self.label.setText(_translate("SensitivitySweepForm", "High Voltage Target"))
        self.hvTargetLabel.setText(_translate("SensitivitySweepForm", "--- V"))
        self.label_8.setText(_translate("SensitivitySweepForm", "High Voltage Measured"))
        self.hvMeasuredLabel.setText(_translate("SensitivitySweepForm", "--- V"))
        self.startButton.setText(_translate("SensitivitySweepForm", "Start"))
        self.stopButton.setText(_translate("SensitivitySweepForm", "Stop"))

